language: python
services:
  - docker

env:
  global:
    - DB_HOST=db
    - DB_PORT=3306

before_install:
  - apt-get update && apt-get install netcat
  - mv env.travis .env
  - docker-compose up --build -d
script:
  - bash ./run_tests.sh
