dst: bionic
language: python
services:
  - docker

env:
  global:
    - DB_HOST=db
    - DB_PORT=3306

before_install:
  - mv env.travis .env
  - docker-compose -f docker-compose-travis.yaml up --build -d
script:
  - bash ./run_tests.sh
