sudo: required
services:
  - docker
  - mysql
  - redis-server
before_install:
  - mv env.travis .env
  - docker build -t eyobofficial/drf-starter .
script:
  - docker container run eyobofficial/drf-starter python manage.py test --no-input
