language: python
python: 3.6
services:
  - docker
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE travis_ci_test;'
  - docker build -t eyobofficial/drf-starter .
script:
  - docker run --net=host --env-file=.env.travis eyobofficial/drf-starter bash ./run_tests.sh
