# services:
# - docker
# - mysql
env:
- SERVER_IP_ADDRESS=167.172.29.127
before_install: # setup the RSA key for use in Dokku Deployment:
- openssl aes-256-cbc -K $encrypted_77965d5bdd4d_key -iv $encrypted_77965d5bdd4d_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
# test ssh connection for: https://github.com/dwyl/learn-travis/issues/42
- ssh -i ./deploy_key root@$SERVER_IP_ADDRESS
- pwd
# before_install:
# - bash ./deploy.sh
# - mysql -e 'CREATE DATABASE travis_ci_test;'
# - docker build -t eyobofficial/drf-starter-django .
install: skip
script: skip
# - docker run --net=host --env-file=.env.travis eyobofficial/drf-starter-django bash
#   ./run_tests.sh
# after_success:
# - docker build -t eyobofficial/drf-starter-nginx -f ./nginx/Dockerfile ./nginx
# - docker login -u $DOCKER_ID -p $DOCKER_PASSWORD
# - docker push eyobofficial/drf-starter-django
# - docker push eyobofficial/drf-starter-nginx
# - echo $USER
# deploy:
#   provider: script
#   script:  ./deploy.sh
#   on:
#     branch: development
