language: python
services:
  - docker
  - mysql
before_install:
  - docker build -t eyobofficial/drf-starter .
script:
  - docker run --net=host --env-file=.env.travis eyobofficial/drf-starter python manage.py test --verbosity 2 --no-input
