version: '3'
services:
  web:
    build: .
    command: bash ./run_tests.sh
    environment:
      DB_HOST: db
      DB_PORT: 3306
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: secret
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
