version: '3'
services:
  web:
    build: .
    command: bash ./run_tests.sh
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: mysql:5.7
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
